### ISSUE TITLE
Team Number Constraint Not Working

### ISSUE THREAD

**Issue by dcodos** [dscotthunter/Fantasy-Hockey-IP-Code#1]
When the code is run as is with the test data, the resulting lineups do not follow the team number constraint, regardless of how many teams are specified.

**Comment by UdayaBhanuG** [comment]
code_for_Github.jl, used_team constraint, allows for used_team always being zero even when the team is used in the IP solution. It could be like, we use 5 teams and make used_team of 3 of those teams zero, and 1 for only other two teams. This makes solution not applicable even though it is correct. Please let me knwo.
