### ISSUE TITLE
trying to run the code

### ISSUE THREAD

**Issue by chris13337** [dscotthunter/Fantasy-Hockey-IP-Code#8]
Hello guys, I have a lot of trouble running the code. Is here anyone who was able to do so? Which Julia Version are you using?

**Comment by kcdc29** [comment]
@chris13337 I've had a lot of issues too and I'm fairly new at this.  I'll let you know if I make any progress!

**Comment by TheNextMyth** [comment]
Were either of you able to get the code working? I've tried as well and have been able to clear a lot of errors but am still stuck.
